name: Build and Deploy
on:
  push:
    branches:
      - main
    paths:
      - 'game/**'
jobs:
  build_web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./game
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11.x'
          cache: gradle

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: 'game/pubspec.yaml'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build
        run: |
          flutter build web --base-href '/word-game-2/' --release
          touch build/web/.nojekyll

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'game/build/web/'

  deploy:
    needs: build_web
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v3
