name: Build PR
on:
  pull_request:
    paths:
      - 'game/**'
jobs:
  # check_version:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: ./game
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
        
  #     - name: Check Version
  #       uses: del-systems/check-if-version-bumped@v2
  #       with:
  #         path: "game/package.json"
        
  build_site:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./game
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: game/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: build
        run: npm run build-web
