name: Build PR
on:
  pull_request:
    paths:
      - 'game/**'
jobs:
  # check_version:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: ./game
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
        
  #     - name: Check Version
  #       uses: del-systems/check-if-version-bumped@v2
  #       with:
  #         path: "game/package.json"
        
  build_web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./game
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          java-version: '11.x'
          cache: gradle

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: "game/pubspec.yaml"
          cache: true

      - name: Get dependencies
        run: fluter pub get
        
      - name: Build
        run: flutter build web
